name: Build and deploy Ionic app to Azure Web App - mkcapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies and build the app
      - name: Install dependencies and build the app
        run: |
          cd myKittyCafe
          npm install
          npm run build --if-present

      # Upload the build artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ionic-app
          path: myKittyCafe/www

  deploy:
    runs-on
