name: Build and deploy Ionic app to Azure Web App - mkcapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies and build the Ionic app
      - name: npm install, build
        run: |
          cd myKittyCafe
          npm install
          npm run build --if-present
      
      # Upload the built artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ionic-app
          path: myKittyCafe/www

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Create www directory first
      - name: Create www directory
        run: |
          mkdir -p www

      # cd into the www directory
      - name: Change into www directory
        run: |
          cd www

      # Download the artifact from the build job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ionic-app

      # List downloaded files for debugging purposes
      - name: List downloaded files
        run: |
          ls -R  # This will help verify the artifact structure in the current directory

      # cd out of the www directory
      - name: cd out of www directory
        run: |
          cd ..

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'mkcapp'  # Replace with your actual app name
          slot-name: 'production'  # You can set this to another slot if needed
          package: ./www  # Path to the built app (www folder)
